name: _exp8403
on: [push]
jobs:
  _exp8403:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: npm i
      - name: Typecheck
        run: npm run typecheck
      - name: Test
        run: npm run test
      - name: Echo
        run: echo "Express!"
